/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BridalRouteImport } from './routes/bridal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SareeSareeIdRouteImport } from './routes/saree.$sareeId'

const BridalRoute = BridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SareeSareeIdRoute = SareeSareeIdRouteImport.update({
  id: '/saree/$sareeId',
  path: '/saree/$sareeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridal': typeof BridalRoute
  '/saree/$sareeId': typeof SareeSareeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridal': typeof BridalRoute
  '/saree/$sareeId': typeof SareeSareeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridal': typeof BridalRoute
  '/saree/$sareeId': typeof SareeSareeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bridal' | '/saree/$sareeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bridal' | '/saree/$sareeId'
  id: '__root__' | '/' | '/bridal' | '/saree/$sareeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridalRoute: typeof BridalRoute
  SareeSareeIdRoute: typeof SareeSareeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bridal': {
      id: '/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof BridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saree/$sareeId': {
      id: '/saree/$sareeId'
      path: '/saree/$sareeId'
      fullPath: '/saree/$sareeId'
      preLoaderRoute: typeof SareeSareeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridalRoute: BridalRoute,
  SareeSareeIdRoute: SareeSareeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
